// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKBOXuMfojzyDiHUjeXblmNP7NuO694pM',
    appId: '1:1057100574922:web:fbc9e0688c991b1a5fc433',
    messagingSenderId: '1057100574922',
    projectId: 'tripplanner77com',
    authDomain: 'tripplanner77com.firebaseapp.com',
    storageBucket: 'tripplanner77com.firebasestorage.app',
    measurementId: 'G-VQGZPJ5V76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2LwWVfbkUflAG1lweBIqvaLK4syay8Go',
    appId: '1:1057100574922:android:382228badd2f57d45fc433',
    messagingSenderId: '1057100574922',
    projectId: 'tripplanner77com',
    storageBucket: 'tripplanner77com.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIZz4cenCzK5SPzhxNzmYZLPQ1Rh0oR4Q',
    appId: '1:1057100574922:ios:d795aeedfd51cbb55fc433',
    messagingSenderId: '1057100574922',
    projectId: 'tripplanner77com',
    storageBucket: 'tripplanner77com.firebasestorage.app',
    androidClientId: '1057100574922-iepb66trclfvukfs2rf3q26c1e0l6qul.apps.googleusercontent.com',
    iosClientId: '1057100574922-amsmeftej3o56978tebb66egm6jhvilh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIZz4cenCzK5SPzhxNzmYZLPQ1Rh0oR4Q',
    appId: '1:1057100574922:ios:d795aeedfd51cbb55fc433',
    messagingSenderId: '1057100574922',
    projectId: 'tripplanner77com',
    storageBucket: 'tripplanner77com.firebasestorage.app',
    androidClientId: '1057100574922-iepb66trclfvukfs2rf3q26c1e0l6qul.apps.googleusercontent.com',
    iosClientId: '1057100574922-amsmeftej3o56978tebb66egm6jhvilh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKBOXuMfojzyDiHUjeXblmNP7NuO694pM',
    appId: '1:1057100574922:web:26e1a3b8e91847785fc433',
    messagingSenderId: '1057100574922',
    projectId: 'tripplanner77com',
    authDomain: 'tripplanner77com.firebaseapp.com',
    storageBucket: 'tripplanner77com.firebasestorage.app',
    measurementId: 'G-JKF2Z6TNVL',
  );
}
